---

- name: Add Nomad repository
  yum_repository:
    name: nomad
    description: add nomad repository
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install Nomad
  yum:
    name: nomad
    state: present
  notify: Template Nomad file
