---
- name: add custom repository
  yum_repository:
    name: consul
    description: add consul repository
    command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install consul
  yum:
    name: consul
    state: installed
  notify: restart consul
  
