---

- name: Download node_exporter
  uri:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz

- name: Extract node_exporter-1.0.1.linux-amd64.tar.gz
  unarchive:
    src: node_exporter-1.0.1.linux-amd64.tar.gz
    dest: ./
    
- name: Node_exporter .service file
  template: 
    src: node_exporter.service.sh.j2
    dest: /etc/systemd/system/node_exporter.service
